#+BEGIN_CENTER
复习题
#+END_CENTER

* 什么是继承？
  继承描述了类和它的扩展类间的关系，扩展包括增加新的字段，新的方法以及
  对原类中方法的重新定义（覆盖）。把原有类称为父类或超类，而扩展类称为
  孩子类或子类。
* 什么是多态？
  多态指一个对象可以以另一个对象的形式来显示其行为，该外表对象与原对象
  实质上是一个对象，只是把它当作其父类或祖先类的一个成员。
* 什么是强制类型转换？
  类型强制转换是一种类型的值当作另一个种类型来使用。对象不能改变它们的
  类型，倡它们的值可以赋予另一种类型的对象，只要这两种类型位于继承树上
  从根到叶的同一条路径上。例如：
  #+BEGIN_SRC java
    String string1 = "ABCDE";
    Object object = (Object)string1;

    String string2 = (String)object;
  #+END_SRC
* 什么是数字提升？
  数值升迁类似于类型强制转换，它应用于基本类型。数字类型的值可以赋予更
  高数字类型的变量。例如：
  #+BEGIN_SRC java
    int n = 44;
    float x = n;
    double y = x;
  #+END_SRC
* 在Java中为什么称Object类是所有其他类的母类（也称父类）？
  在Java中Object类是唯一没有父类的类，它是Java继承树的根。
* 什么是抽象方法？
  一个抽象方法只是一个简单的函数声明：包含方法修饰符，返回类型及其方法
  签名(signature)。
* 什么是抽象类？
  一个抽象类是至少有一个抽象方法的类。
* 什么是抽象类和接口的差异？
  一个抽象类可以有字段和一些已实现的方法，一个接口完全没有实现，只有常
  量和方法声明。
* 什么是子类和类扩展的差异？
  一个子类和类扩展间没有什么区别，它们是同义词。
* 什么是接口和抽象类的差异？
  一个接口是没有任何实现的类，也就是说，只是一系列的方法签名，没有任何
  可执行的语句和字段定义。抽象类除了有一些实现方法和某些字段定义外，与
  接口相同。抽象类中没有实现的方法在声明时应当用abstract关键字限定。
* 什么是扩展另一个类的类与实现某个接口的类间的差异？
  当一个类扩展另一个类时，它继承父类的所有方法（覆盖的除外）。当一个类
  是实现一个接口时，它应当实现接口中所有的方法声明。
* 什么是一个try块？
  一个try块是try .. catch 语句中紧跟在try关键字之后的语句块，这是引发
  检查异常的方法所在的语句块，并且应当进行异常处理，除非方法本身将异常
  返回到调用它的更外层方法进行处理。
* 什么是被检查异常与不检查异常的区别？
  一个检查异常是一个必须捕获的异常，可由方法所在位置进行或由调用树中更
  外层的方法进行处理。引发检查异常的方法只能在try块中调用或由抛出异常
  的其他方法所调用。唯一不检查的异常是由RuntimeException类的后代类所引
  发的异常。
