#+BEGIN_CENTER
知识点备忘
#+END_CENTER

1. 数组是一个对象，可以使用Object.clone()方法对它进行复制。
   #+BEGIN_SRC java
     {
         int[] a = { 22, 44, 66, 88};

         int[] b = (int[])a.clone(); //duplicate a[] in b[]
     }   
   #+END_SRC

2. Arrays是操作array的辅助类。



#+BEGIN_CENTER
复习题
#+END_CENTER

* 数组元素中的基元与成分的不同是什么？

  数组的成分可以是任何类型：基本类型、引用或数组。一个数组元素是本身本
  身不是数组类型的成份。因此，对a[][]而言，数组a[]的成份为行数组，而
  a[][]的元素为double变量。

* 说Java不允许多维数组时指的是什么？

  多维数组是一个有2个或2个以上下标值的数组。一个Java数组是只有一个下标
  变量的数组。然而，变量所标识的是一个本身又是数组的成份（有一个下标），
  因此，原数组似乎有多于一个的下标。

* 异常ArrayIndexOutOfBoundsException是什么？它在使Java区别于其他语言如C和C++方面有什么作用？

  ArrayIndexOutOfBoundsException对象是一个异常，该异常在用小于0，大于
  或等于数组长度下标值对数组进行访问时发生。这给程序员对运行时的错误控
  制提供了某种手段，在如C++的程序设计语言中，这样的错误往往导致程序崩
  溃。

* 数组索引的类型可以是哪些？

  数组的下标类型可以是byte,char,short或int。

* 以下定义中有什么错误？
  : Arrays arryas = new Arrays();

  Arrays类不能被实例化，这是由于它的构造函数是私有的(private)。

* 打印一个对象数组的简单方法是什么？

  打印对象数组的最简单的方式是将它作为参数传递给Arrays.toList()方法，
  它将对象数组转换为一个List对象，该List对象可以用System.out.println()
  方法进行直接打印输出。

* 如果说折半查找远快于顺序查找，为什么后者还会被使用？

  折半查找将不能工作，除非首先对序列进行排序 。

* 在数组中，当某元素重复出现时，使用顺序查找会发生什么情况？

  如果顺序查找算法能生地查找数组中的某个不止出现一次的元素，它将返回最
  靠近数组开始位置的下标。

* 在数组中，当某元素重复出现时，使用折半查找会发生什么情况？

  如果折半查找算法用于查找数组中茜个不止出现一次的元素，它可能返回这些
  重复元素中的任意一个的下标，它取决于离子区间中心点的远近。例如，如果
  折半查找算法用于查找一个有10000个元素的数组，查找一个位于0到99间的重
  复值，查找算法将在第7次返回下标索引77.

* 对一个向量 对象调用clear()方法与将该对象设置为null有什么不同？

  方法调用v.clear()将使向量v成为一个空向量，空向量仍是一个非空对象，但
  赋值语句v=null将使得对象引用为空，并使得原有对象消灭。在前一种情况下，
  表达式v.size()的值为0，而在后一种情况下，表达式v.size()将导致异常的
  产生。
