 #+BEGIN_CENTER
 复习题
 #+END_CENTER

* 为什么说Java是一种面向对象的语言？

  Java被称为面向对象的程序设计语言是因为所有的数据和操作都封装在对象中，
  而且对象的类均在一个单继承的层次结构中定义。

* 对一个Java程序来说，什么是必需的？

  一个Java程序必须有一个public类，该类定义是名为X.java的文件中，这里的
  X是类名，类必须包括一个如下所示的方法：
: public static void main(String[] args);

* 基本类型是什么？

  一个基本类型是指以下类型之一： boolean, char, byte, short, int,
  long, float, double.

* 什么是文字？

  文字是一个没有名字的常量，是表示该类型值的一个符号。例如，44,3.14以
  及"East Anglia"均为文字。

* 对两个浮点数据类型而言，3个非数据文字是什么？

  浮点数类型的3个非数字文字是 =NEGATIVE_INFINITY= ,
  =POSITIVE_INFINITY= 以及 NaN。

* 什么是对象引用？

  对象引用是一个变量，其值要么为空，要么是某个对象的地址。

* 什么是对象？

  对象在内存中是一块连续的存储区，其类型由类所确定并通过该类的一个引用
  变量进行存取。对象可以包含保存数据的数据字段和完成操作的方法。

* 什么是类？

  类是创建对象的蓝图，类定义中说明了类实例对象的数据字段和方法。

* 什么是实例？

  一个类的实例是该类所说明的类型的一个对象，一个实例的创建也称为类的实
  例化。

* 什么是field成员？

  一个field是类的一个成员变量，当类实例化以后，结果对象的field用于保存
  对象的数据。

* 方法是什么？

  方法是类的成员函数，当类实例化后，结果对象的方法将为对象完成各种操作。

* 方法的说明指什么？

  方法说明是方法定义的一部分，编译器需要这些信息来对调用该方法的语句进
  行编译处理。例如，主方法的说明为 main(String[])。

* 什么是构造函数？

  构造函数是类的一个方法，对类进行实例化。它的名字与类相同并且没有返回
  类型，它由new运算符进行调用。

* 什么是静态成员？

  一个类的静态成员是应用于整个类而不是类的某个特定对象的成员，它用类名
  而不是某个对象名进行调用。例如，类Math中的方法sqrt(double)就是一个静
  态方法，它以Math.sqrt()的形式进行调用。一个静态字段仅有一个数据值而
  不管有多少个对象（或没有实例对象）。

* 存取描述 符有哪些？

  存取描述符指Java中的以下3个保留字：public, protected或private，它们
  对类、字段、方法、接口等进行访问限制说明。

* 存取描述符中的private是什么含义？

  存取描述符private指该修饰实体只能在所在类的范围内进行访问。

* 存取描述符中的protected是什么含义？

  存取描述符中的protected是指该修饰实体只能在被定义的类的范围或该类的
  子类中进行访问。

* 什么是包装类？

  包装类也是一个类，其目的是为处理8个基本类型中的某个数据类型提供常量
  和方法。例如Double类就是为double基本类型而定义的包装类。

* 是什么使得String类与Java标准库中的其他 类如此不同？

  String类与Java标准类库中的其他类不同，因为它的实例是不能改变的（只能
  读），它的文字 具有惟一性并有两个进行串接操作的运算符+和+=。

* Math.random()方法的作用是什么？
  
  Math.random()方法返回一个在0.0~1.0之间进行均匀分布的随机双精度浮点数。
